// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package da_generated

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.getUserByUsernameEmailStmt, err = db.PrepareContext(ctx, getUserByUsernameEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByUsernameEmail: %w", err)
	}
	if q.getUserByUsernamePhoneNumberStmt, err = db.PrepareContext(ctx, getUserByUsernamePhoneNumber); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByUsernamePhoneNumber: %w", err)
	}
	if q.getUserByUsernameUsernameStmt, err = db.PrepareContext(ctx, getUserByUsernameUsername); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByUsernameUsername: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.getUserByUsernameEmailStmt != nil {
		if cerr := q.getUserByUsernameEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByUsernameEmailStmt: %w", cerr)
		}
	}
	if q.getUserByUsernamePhoneNumberStmt != nil {
		if cerr := q.getUserByUsernamePhoneNumberStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByUsernamePhoneNumberStmt: %w", cerr)
		}
	}
	if q.getUserByUsernameUsernameStmt != nil {
		if cerr := q.getUserByUsernameUsernameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByUsernameUsernameStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                               DBTX
	tx                               *sql.Tx
	createUserStmt                   *sql.Stmt
	getUserByUsernameEmailStmt       *sql.Stmt
	getUserByUsernamePhoneNumberStmt *sql.Stmt
	getUserByUsernameUsernameStmt    *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                               tx,
		tx:                               tx,
		createUserStmt:                   q.createUserStmt,
		getUserByUsernameEmailStmt:       q.getUserByUsernameEmailStmt,
		getUserByUsernamePhoneNumberStmt: q.getUserByUsernamePhoneNumberStmt,
		getUserByUsernameUsernameStmt:    q.getUserByUsernameUsernameStmt,
	}
}
