// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package da_generated

import (
	"database/sql"
	"encoding/json"
	"time"
)

type User struct {
	ID       int64          `json:"id"`
	Username sql.NullString `json:"username"`
	// format 84914123423
	PhoneNumber sql.NullString `json:"phone_number"`
	Email       sql.NullString `json:"email"`
	// birthday,...
	PersonalInfo json.RawMessage `json:"personal_info"`
	FullName     string          `json:"full_name"`
	// hashed password
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
