// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package da_generated

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg *CreateAccountParams) (sql.Result, error)
	GetAccountByEmail(ctx context.Context, email sql.NullString) (*Account, error)
	GetAccountByPhoneNumber(ctx context.Context, phoneNumber sql.NullString) (*Account, error)
	GetAccountByUsername(ctx context.Context, username sql.NullString) (*Account, error)
}

var _ Querier = (*Queries)(nil)
