// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package da_generated

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateUser(ctx context.Context, arg *CreateUserParams) (sql.Result, error)
	GetUserByUsernameEmail(ctx context.Context, email sql.NullString) (*User, error)
	GetUserByUsernamePhoneNumber(ctx context.Context, phoneNumber sql.NullString) (*User, error)
	GetUserByUsernameUsername(ctx context.Context, username sql.NullString) (*User, error)
}

var _ Querier = (*Queries)(nil)
