version: "3.8"

services:
  mysql:
    image: arm64v8/mysql:oracle
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=financial_service
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=pwd123
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - service_network
  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
    ports:
      - '6379:6379'

networks:
  service_network:
    driver: bridge