// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: promotion/admin.proto

package promotion

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SetVoucherToCampaignRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SetVoucherToCampaignRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SetVoucherToCampaignRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SetVoucherToCampaignRequestMultiError, or nil if none found.
func (m *SetVoucherToCampaignRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SetVoucherToCampaignRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CampaignId

	for idx, item := range m.GetVouchers() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SetVoucherToCampaignRequestValidationError{
						field:  fmt.Sprintf("Vouchers[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SetVoucherToCampaignRequestValidationError{
						field:  fmt.Sprintf("Vouchers[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SetVoucherToCampaignRequestValidationError{
					field:  fmt.Sprintf("Vouchers[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return SetVoucherToCampaignRequestMultiError(errors)
	}

	return nil
}

// SetVoucherToCampaignRequestMultiError is an error wrapping multiple
// validation errors returned by SetVoucherToCampaignRequest.ValidateAll() if
// the designated constraints aren't met.
type SetVoucherToCampaignRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SetVoucherToCampaignRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SetVoucherToCampaignRequestMultiError) AllErrors() []error { return m }

// SetVoucherToCampaignRequestValidationError is the validation error returned
// by SetVoucherToCampaignRequest.Validate if the designated constraints
// aren't met.
type SetVoucherToCampaignRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetVoucherToCampaignRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetVoucherToCampaignRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetVoucherToCampaignRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetVoucherToCampaignRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetVoucherToCampaignRequestValidationError) ErrorName() string {
	return "SetVoucherToCampaignRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SetVoucherToCampaignRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetVoucherToCampaignRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetVoucherToCampaignRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetVoucherToCampaignRequestValidationError{}

// Validate checks the field values on SetVoucherToCampaignReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SetVoucherToCampaignReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SetVoucherToCampaignReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SetVoucherToCampaignReplyMultiError, or nil if none found.
func (m *SetVoucherToCampaignReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SetVoucherToCampaignReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if len(errors) > 0 {
		return SetVoucherToCampaignReplyMultiError(errors)
	}

	return nil
}

// SetVoucherToCampaignReplyMultiError is an error wrapping multiple validation
// errors returned by SetVoucherToCampaignReply.ValidateAll() if the
// designated constraints aren't met.
type SetVoucherToCampaignReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SetVoucherToCampaignReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SetVoucherToCampaignReplyMultiError) AllErrors() []error { return m }

// SetVoucherToCampaignReplyValidationError is the validation error returned by
// SetVoucherToCampaignReply.Validate if the designated constraints aren't met.
type SetVoucherToCampaignReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetVoucherToCampaignReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetVoucherToCampaignReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetVoucherToCampaignReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetVoucherToCampaignReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetVoucherToCampaignReplyValidationError) ErrorName() string {
	return "SetVoucherToCampaignReplyValidationError"
}

// Error satisfies the builtin error interface
func (e SetVoucherToCampaignReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetVoucherToCampaignReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetVoucherToCampaignReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetVoucherToCampaignReplyValidationError{}

// Validate checks the field values on DefineVoucherRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DefineVoucherRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DefineVoucherRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DefineVoucherRequestMultiError, or nil if none found.
func (m *DefineVoucherRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DefineVoucherRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for VoucherType

	// no validation rules for Amount

	// no validation rules for ExpirationTime

	// no validation rules for AppId

	if len(errors) > 0 {
		return DefineVoucherRequestMultiError(errors)
	}

	return nil
}

// DefineVoucherRequestMultiError is an error wrapping multiple validation
// errors returned by DefineVoucherRequest.ValidateAll() if the designated
// constraints aren't met.
type DefineVoucherRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DefineVoucherRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DefineVoucherRequestMultiError) AllErrors() []error { return m }

// DefineVoucherRequestValidationError is the validation error returned by
// DefineVoucherRequest.Validate if the designated constraints aren't met.
type DefineVoucherRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DefineVoucherRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DefineVoucherRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DefineVoucherRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DefineVoucherRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DefineVoucherRequestValidationError) ErrorName() string {
	return "DefineVoucherRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DefineVoucherRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDefineVoucherRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DefineVoucherRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DefineVoucherRequestValidationError{}

// Validate checks the field values on DefineVoucherReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DefineVoucherReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DefineVoucherReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DefineVoucherReplyMultiError, or nil if none found.
func (m *DefineVoucherReply) ValidateAll() error {
	return m.validate(true)
}

func (m *DefineVoucherReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if len(errors) > 0 {
		return DefineVoucherReplyMultiError(errors)
	}

	return nil
}

// DefineVoucherReplyMultiError is an error wrapping multiple validation errors
// returned by DefineVoucherReply.ValidateAll() if the designated constraints
// aren't met.
type DefineVoucherReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DefineVoucherReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DefineVoucherReplyMultiError) AllErrors() []error { return m }

// DefineVoucherReplyValidationError is the validation error returned by
// DefineVoucherReply.Validate if the designated constraints aren't met.
type DefineVoucherReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DefineVoucherReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DefineVoucherReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DefineVoucherReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DefineVoucherReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DefineVoucherReplyValidationError) ErrorName() string {
	return "DefineVoucherReplyValidationError"
}

// Error satisfies the builtin error interface
func (e DefineVoucherReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDefineVoucherReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DefineVoucherReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DefineVoucherReplyValidationError{}

// Validate checks the field values on DefineCampaignRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DefineCampaignRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DefineCampaignRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DefineCampaignRequestMultiError, or nil if none found.
func (m *DefineCampaignRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DefineCampaignRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CampaignKey

	// no validation rules for Name

	if len(errors) > 0 {
		return DefineCampaignRequestMultiError(errors)
	}

	return nil
}

// DefineCampaignRequestMultiError is an error wrapping multiple validation
// errors returned by DefineCampaignRequest.ValidateAll() if the designated
// constraints aren't met.
type DefineCampaignRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DefineCampaignRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DefineCampaignRequestMultiError) AllErrors() []error { return m }

// DefineCampaignRequestValidationError is the validation error returned by
// DefineCampaignRequest.Validate if the designated constraints aren't met.
type DefineCampaignRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DefineCampaignRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DefineCampaignRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DefineCampaignRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DefineCampaignRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DefineCampaignRequestValidationError) ErrorName() string {
	return "DefineCampaignRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DefineCampaignRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDefineCampaignRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DefineCampaignRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DefineCampaignRequestValidationError{}

// Validate checks the field values on DefineCampaignReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DefineCampaignReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DefineCampaignReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DefineCampaignReplyMultiError, or nil if none found.
func (m *DefineCampaignReply) ValidateAll() error {
	return m.validate(true)
}

func (m *DefineCampaignReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if len(errors) > 0 {
		return DefineCampaignReplyMultiError(errors)
	}

	return nil
}

// DefineCampaignReplyMultiError is an error wrapping multiple validation
// errors returned by DefineCampaignReply.ValidateAll() if the designated
// constraints aren't met.
type DefineCampaignReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DefineCampaignReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DefineCampaignReplyMultiError) AllErrors() []error { return m }

// DefineCampaignReplyValidationError is the validation error returned by
// DefineCampaignReply.Validate if the designated constraints aren't met.
type DefineCampaignReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DefineCampaignReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DefineCampaignReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DefineCampaignReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DefineCampaignReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DefineCampaignReplyValidationError) ErrorName() string {
	return "DefineCampaignReplyValidationError"
}

// Error satisfies the builtin error interface
func (e DefineCampaignReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDefineCampaignReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DefineCampaignReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DefineCampaignReplyValidationError{}

// Validate checks the field values on SetVoucherToCampaignRequest_Voucher with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *SetVoucherToCampaignRequest_Voucher) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SetVoucherToCampaignRequest_Voucher
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// SetVoucherToCampaignRequest_VoucherMultiError, or nil if none found.
func (m *SetVoucherToCampaignRequest_Voucher) ValidateAll() error {
	return m.validate(true)
}

func (m *SetVoucherToCampaignRequest_Voucher) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for VoucherId

	// no validation rules for Amount

	if len(errors) > 0 {
		return SetVoucherToCampaignRequest_VoucherMultiError(errors)
	}

	return nil
}

// SetVoucherToCampaignRequest_VoucherMultiError is an error wrapping multiple
// validation errors returned by
// SetVoucherToCampaignRequest_Voucher.ValidateAll() if the designated
// constraints aren't met.
type SetVoucherToCampaignRequest_VoucherMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SetVoucherToCampaignRequest_VoucherMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SetVoucherToCampaignRequest_VoucherMultiError) AllErrors() []error { return m }

// SetVoucherToCampaignRequest_VoucherValidationError is the validation error
// returned by SetVoucherToCampaignRequest_Voucher.Validate if the designated
// constraints aren't met.
type SetVoucherToCampaignRequest_VoucherValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetVoucherToCampaignRequest_VoucherValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetVoucherToCampaignRequest_VoucherValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetVoucherToCampaignRequest_VoucherValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetVoucherToCampaignRequest_VoucherValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetVoucherToCampaignRequest_VoucherValidationError) ErrorName() string {
	return "SetVoucherToCampaignRequest_VoucherValidationError"
}

// Error satisfies the builtin error interface
func (e SetVoucherToCampaignRequest_VoucherValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetVoucherToCampaignRequest_Voucher.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetVoucherToCampaignRequest_VoucherValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetVoucherToCampaignRequest_VoucherValidationError{}
