// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: promotion/admin.proto

package promotion

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on DefineVoucherRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DefineVoucherRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DefineVoucherRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DefineVoucherRequestMultiError, or nil if none found.
func (m *DefineVoucherRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DefineVoucherRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for IsActive

	// no validation rules for Description

	if all {
		switch v := interface{}(m.GetMetadata()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DefineVoucherRequestValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DefineVoucherRequestValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMetadata()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DefineVoucherRequestValidationError{
				field:  "Metadata",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DefineVoucherRequestMultiError(errors)
	}

	return nil
}

// DefineVoucherRequestMultiError is an error wrapping multiple validation
// errors returned by DefineVoucherRequest.ValidateAll() if the designated
// constraints aren't met.
type DefineVoucherRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DefineVoucherRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DefineVoucherRequestMultiError) AllErrors() []error { return m }

// DefineVoucherRequestValidationError is the validation error returned by
// DefineVoucherRequest.Validate if the designated constraints aren't met.
type DefineVoucherRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DefineVoucherRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DefineVoucherRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DefineVoucherRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DefineVoucherRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DefineVoucherRequestValidationError) ErrorName() string {
	return "DefineVoucherRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DefineVoucherRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDefineVoucherRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DefineVoucherRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DefineVoucherRequestValidationError{}

// Validate checks the field values on VoucherMetadata with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *VoucherMetadata) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VoucherMetadata with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// VoucherMetadataMultiError, or nil if none found.
func (m *VoucherMetadata) ValidateAll() error {
	return m.validate(true)
}

func (m *VoucherMetadata) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetExpirationTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, VoucherMetadataValidationError{
					field:  "ExpirationTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, VoucherMetadataValidationError{
					field:  "ExpirationTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetExpirationTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VoucherMetadataValidationError{
				field:  "ExpirationTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetStrategy()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, VoucherMetadataValidationError{
					field:  "Strategy",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, VoucherMetadataValidationError{
					field:  "Strategy",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStrategy()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VoucherMetadataValidationError{
				field:  "Strategy",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return VoucherMetadataMultiError(errors)
	}

	return nil
}

// VoucherMetadataMultiError is an error wrapping multiple validation errors
// returned by VoucherMetadata.ValidateAll() if the designated constraints
// aren't met.
type VoucherMetadataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VoucherMetadataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VoucherMetadataMultiError) AllErrors() []error { return m }

// VoucherMetadataValidationError is the validation error returned by
// VoucherMetadata.Validate if the designated constraints aren't met.
type VoucherMetadataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VoucherMetadataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VoucherMetadataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VoucherMetadataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VoucherMetadataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VoucherMetadataValidationError) ErrorName() string { return "VoucherMetadataValidationError" }

// Error satisfies the builtin error interface
func (e VoucherMetadataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVoucherMetadata.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VoucherMetadataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VoucherMetadataValidationError{}

// Validate checks the field values on VoucherStrategy with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *VoucherStrategy) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VoucherStrategy with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// VoucherStrategyMultiError, or nil if none found.
func (m *VoucherStrategy) ValidateAll() error {
	return m.validate(true)
}

func (m *VoucherStrategy) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	switch v := m.Metadata.(type) {
	case *VoucherStrategy_FixedAmountForAppIds:
		if v == nil {
			err := VoucherStrategyValidationError{
				field:  "Metadata",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetFixedAmountForAppIds()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, VoucherStrategyValidationError{
						field:  "FixedAmountForAppIds",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, VoucherStrategyValidationError{
						field:  "FixedAmountForAppIds",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetFixedAmountForAppIds()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return VoucherStrategyValidationError{
					field:  "FixedAmountForAppIds",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *VoucherStrategy_PercentageDiscountForAppIds:
		if v == nil {
			err := VoucherStrategyValidationError{
				field:  "Metadata",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetPercentageDiscountForAppIds()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, VoucherStrategyValidationError{
						field:  "PercentageDiscountForAppIds",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, VoucherStrategyValidationError{
						field:  "PercentageDiscountForAppIds",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetPercentageDiscountForAppIds()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return VoucherStrategyValidationError{
					field:  "PercentageDiscountForAppIds",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return VoucherStrategyMultiError(errors)
	}

	return nil
}

// VoucherStrategyMultiError is an error wrapping multiple validation errors
// returned by VoucherStrategy.ValidateAll() if the designated constraints
// aren't met.
type VoucherStrategyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VoucherStrategyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VoucherStrategyMultiError) AllErrors() []error { return m }

// VoucherStrategyValidationError is the validation error returned by
// VoucherStrategy.Validate if the designated constraints aren't met.
type VoucherStrategyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VoucherStrategyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VoucherStrategyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VoucherStrategyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VoucherStrategyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VoucherStrategyValidationError) ErrorName() string { return "VoucherStrategyValidationError" }

// Error satisfies the builtin error interface
func (e VoucherStrategyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVoucherStrategy.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VoucherStrategyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VoucherStrategyValidationError{}

// Validate checks the field values on VoucherStrategyFixedAmountForAppIds with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *VoucherStrategyFixedAmountForAppIds) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VoucherStrategyFixedAmountForAppIds
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// VoucherStrategyFixedAmountForAppIdsMultiError, or nil if none found.
func (m *VoucherStrategyFixedAmountForAppIds) ValidateAll() error {
	return m.validate(true)
}

func (m *VoucherStrategyFixedAmountForAppIds) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Percentage

	if len(errors) > 0 {
		return VoucherStrategyFixedAmountForAppIdsMultiError(errors)
	}

	return nil
}

// VoucherStrategyFixedAmountForAppIdsMultiError is an error wrapping multiple
// validation errors returned by
// VoucherStrategyFixedAmountForAppIds.ValidateAll() if the designated
// constraints aren't met.
type VoucherStrategyFixedAmountForAppIdsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VoucherStrategyFixedAmountForAppIdsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VoucherStrategyFixedAmountForAppIdsMultiError) AllErrors() []error { return m }

// VoucherStrategyFixedAmountForAppIdsValidationError is the validation error
// returned by VoucherStrategyFixedAmountForAppIds.Validate if the designated
// constraints aren't met.
type VoucherStrategyFixedAmountForAppIdsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VoucherStrategyFixedAmountForAppIdsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VoucherStrategyFixedAmountForAppIdsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VoucherStrategyFixedAmountForAppIdsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VoucherStrategyFixedAmountForAppIdsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VoucherStrategyFixedAmountForAppIdsValidationError) ErrorName() string {
	return "VoucherStrategyFixedAmountForAppIdsValidationError"
}

// Error satisfies the builtin error interface
func (e VoucherStrategyFixedAmountForAppIdsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVoucherStrategyFixedAmountForAppIds.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VoucherStrategyFixedAmountForAppIdsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VoucherStrategyFixedAmountForAppIdsValidationError{}

// Validate checks the field values on
// VoucherStrategyPercentageDiscountForAppIds with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *VoucherStrategyPercentageDiscountForAppIds) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// VoucherStrategyPercentageDiscountForAppIds with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in
// VoucherStrategyPercentageDiscountForAppIdsMultiError, or nil if none found.
func (m *VoucherStrategyPercentageDiscountForAppIds) ValidateAll() error {
	return m.validate(true)
}

func (m *VoucherStrategyPercentageDiscountForAppIds) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Percentage

	if len(errors) > 0 {
		return VoucherStrategyPercentageDiscountForAppIdsMultiError(errors)
	}

	return nil
}

// VoucherStrategyPercentageDiscountForAppIdsMultiError is an error wrapping
// multiple validation errors returned by
// VoucherStrategyPercentageDiscountForAppIds.ValidateAll() if the designated
// constraints aren't met.
type VoucherStrategyPercentageDiscountForAppIdsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VoucherStrategyPercentageDiscountForAppIdsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VoucherStrategyPercentageDiscountForAppIdsMultiError) AllErrors() []error { return m }

// VoucherStrategyPercentageDiscountForAppIdsValidationError is the validation
// error returned by VoucherStrategyPercentageDiscountForAppIds.Validate if
// the designated constraints aren't met.
type VoucherStrategyPercentageDiscountForAppIdsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VoucherStrategyPercentageDiscountForAppIdsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VoucherStrategyPercentageDiscountForAppIdsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VoucherStrategyPercentageDiscountForAppIdsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VoucherStrategyPercentageDiscountForAppIdsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VoucherStrategyPercentageDiscountForAppIdsValidationError) ErrorName() string {
	return "VoucherStrategyPercentageDiscountForAppIdsValidationError"
}

// Error satisfies the builtin error interface
func (e VoucherStrategyPercentageDiscountForAppIdsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVoucherStrategyPercentageDiscountForAppIds.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VoucherStrategyPercentageDiscountForAppIdsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VoucherStrategyPercentageDiscountForAppIdsValidationError{}

// Validate checks the field values on DefineVoucherReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DefineVoucherReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DefineVoucherReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DefineVoucherReplyMultiError, or nil if none found.
func (m *DefineVoucherReply) ValidateAll() error {
	return m.validate(true)
}

func (m *DefineVoucherReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if len(errors) > 0 {
		return DefineVoucherReplyMultiError(errors)
	}

	return nil
}

// DefineVoucherReplyMultiError is an error wrapping multiple validation errors
// returned by DefineVoucherReply.ValidateAll() if the designated constraints
// aren't met.
type DefineVoucherReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DefineVoucherReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DefineVoucherReplyMultiError) AllErrors() []error { return m }

// DefineVoucherReplyValidationError is the validation error returned by
// DefineVoucherReply.Validate if the designated constraints aren't met.
type DefineVoucherReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DefineVoucherReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DefineVoucherReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DefineVoucherReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DefineVoucherReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DefineVoucherReplyValidationError) ErrorName() string {
	return "DefineVoucherReplyValidationError"
}

// Error satisfies the builtin error interface
func (e DefineVoucherReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDefineVoucherReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DefineVoucherReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DefineVoucherReplyValidationError{}

// Validate checks the field values on DefineCampaignRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DefineCampaignRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DefineCampaignRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DefineCampaignRequestMultiError, or nil if none found.
func (m *DefineCampaignRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DefineCampaignRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetMetadata()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DefineCampaignRequestValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DefineCampaignRequestValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMetadata()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DefineCampaignRequestValidationError{
				field:  "Metadata",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DefineCampaignRequestMultiError(errors)
	}

	return nil
}

// DefineCampaignRequestMultiError is an error wrapping multiple validation
// errors returned by DefineCampaignRequest.ValidateAll() if the designated
// constraints aren't met.
type DefineCampaignRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DefineCampaignRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DefineCampaignRequestMultiError) AllErrors() []error { return m }

// DefineCampaignRequestValidationError is the validation error returned by
// DefineCampaignRequest.Validate if the designated constraints aren't met.
type DefineCampaignRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DefineCampaignRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DefineCampaignRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DefineCampaignRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DefineCampaignRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DefineCampaignRequestValidationError) ErrorName() string {
	return "DefineCampaignRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DefineCampaignRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDefineCampaignRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DefineCampaignRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DefineCampaignRequestValidationError{}

// Validate checks the field values on CampaignMetadata with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CampaignMetadata) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CampaignMetadata with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CampaignMetadataMultiError, or nil if none found.
func (m *CampaignMetadata) ValidateAll() error {
	return m.validate(true)
}

func (m *CampaignMetadata) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetStartAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CampaignMetadataValidationError{
					field:  "StartAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CampaignMetadataValidationError{
					field:  "StartAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CampaignMetadataValidationError{
				field:  "StartAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetEndAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CampaignMetadataValidationError{
					field:  "EndAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CampaignMetadataValidationError{
					field:  "EndAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEndAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CampaignMetadataValidationError{
				field:  "EndAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetStrategy()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CampaignMetadataValidationError{
					field:  "Strategy",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CampaignMetadataValidationError{
					field:  "Strategy",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStrategy()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CampaignMetadataValidationError{
				field:  "Strategy",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CampaignMetadataMultiError(errors)
	}

	return nil
}

// CampaignMetadataMultiError is an error wrapping multiple validation errors
// returned by CampaignMetadata.ValidateAll() if the designated constraints
// aren't met.
type CampaignMetadataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CampaignMetadataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CampaignMetadataMultiError) AllErrors() []error { return m }

// CampaignMetadataValidationError is the validation error returned by
// CampaignMetadata.Validate if the designated constraints aren't met.
type CampaignMetadataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CampaignMetadataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CampaignMetadataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CampaignMetadataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CampaignMetadataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CampaignMetadataValidationError) ErrorName() string { return "CampaignMetadataValidationError" }

// Error satisfies the builtin error interface
func (e CampaignMetadataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCampaignMetadata.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CampaignMetadataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CampaignMetadataValidationError{}

// Validate checks the field values on CampaignStrategy with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CampaignStrategy) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CampaignStrategy with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CampaignStrategyMultiError, or nil if none found.
func (m *CampaignStrategy) ValidateAll() error {
	return m.validate(true)
}

func (m *CampaignStrategy) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	switch v := m.Metadata.(type) {
	case *CampaignStrategy_StrategyTopRegister:
		if v == nil {
			err := CampaignStrategyValidationError{
				field:  "Metadata",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetStrategyTopRegister()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CampaignStrategyValidationError{
						field:  "StrategyTopRegister",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CampaignStrategyValidationError{
						field:  "StrategyTopRegister",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetStrategyTopRegister()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CampaignStrategyValidationError{
					field:  "StrategyTopRegister",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *CampaignStrategy_StrategySpending:
		if v == nil {
			err := CampaignStrategyValidationError{
				field:  "Metadata",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetStrategySpending()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CampaignStrategyValidationError{
						field:  "StrategySpending",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CampaignStrategyValidationError{
						field:  "StrategySpending",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetStrategySpending()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CampaignStrategyValidationError{
					field:  "StrategySpending",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return CampaignStrategyMultiError(errors)
	}

	return nil
}

// CampaignStrategyMultiError is an error wrapping multiple validation errors
// returned by CampaignStrategy.ValidateAll() if the designated constraints
// aren't met.
type CampaignStrategyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CampaignStrategyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CampaignStrategyMultiError) AllErrors() []error { return m }

// CampaignStrategyValidationError is the validation error returned by
// CampaignStrategy.Validate if the designated constraints aren't met.
type CampaignStrategyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CampaignStrategyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CampaignStrategyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CampaignStrategyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CampaignStrategyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CampaignStrategyValidationError) ErrorName() string { return "CampaignStrategyValidationError" }

// Error satisfies the builtin error interface
func (e CampaignStrategyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCampaignStrategy.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CampaignStrategyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CampaignStrategyValidationError{}

// Validate checks the field values on CampaignStrategyTopRegister with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CampaignStrategyTopRegister) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CampaignStrategyTopRegister with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CampaignStrategyTopRegisterMultiError, or nil if none found.
func (m *CampaignStrategyTopRegister) ValidateAll() error {
	return m.validate(true)
}

func (m *CampaignStrategyTopRegister) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetVouchers() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CampaignStrategyTopRegisterValidationError{
						field:  fmt.Sprintf("Vouchers[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CampaignStrategyTopRegisterValidationError{
						field:  fmt.Sprintf("Vouchers[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CampaignStrategyTopRegisterValidationError{
					field:  fmt.Sprintf("Vouchers[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for TopUsers

	if len(errors) > 0 {
		return CampaignStrategyTopRegisterMultiError(errors)
	}

	return nil
}

// CampaignStrategyTopRegisterMultiError is an error wrapping multiple
// validation errors returned by CampaignStrategyTopRegister.ValidateAll() if
// the designated constraints aren't met.
type CampaignStrategyTopRegisterMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CampaignStrategyTopRegisterMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CampaignStrategyTopRegisterMultiError) AllErrors() []error { return m }

// CampaignStrategyTopRegisterValidationError is the validation error returned
// by CampaignStrategyTopRegister.Validate if the designated constraints
// aren't met.
type CampaignStrategyTopRegisterValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CampaignStrategyTopRegisterValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CampaignStrategyTopRegisterValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CampaignStrategyTopRegisterValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CampaignStrategyTopRegisterValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CampaignStrategyTopRegisterValidationError) ErrorName() string {
	return "CampaignStrategyTopRegisterValidationError"
}

// Error satisfies the builtin error interface
func (e CampaignStrategyTopRegisterValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCampaignStrategyTopRegister.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CampaignStrategyTopRegisterValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CampaignStrategyTopRegisterValidationError{}

// Validate checks the field values on CampaignStrategySpending with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CampaignStrategySpending) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CampaignStrategySpending with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CampaignStrategySpendingMultiError, or nil if none found.
func (m *CampaignStrategySpending) ValidateAll() error {
	return m.validate(true)
}

func (m *CampaignStrategySpending) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return CampaignStrategySpendingMultiError(errors)
	}

	return nil
}

// CampaignStrategySpendingMultiError is an error wrapping multiple validation
// errors returned by CampaignStrategySpending.ValidateAll() if the designated
// constraints aren't met.
type CampaignStrategySpendingMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CampaignStrategySpendingMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CampaignStrategySpendingMultiError) AllErrors() []error { return m }

// CampaignStrategySpendingValidationError is the validation error returned by
// CampaignStrategySpending.Validate if the designated constraints aren't met.
type CampaignStrategySpendingValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CampaignStrategySpendingValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CampaignStrategySpendingValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CampaignStrategySpendingValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CampaignStrategySpendingValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CampaignStrategySpendingValidationError) ErrorName() string {
	return "CampaignStrategySpendingValidationError"
}

// Error satisfies the builtin error interface
func (e CampaignStrategySpendingValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCampaignStrategySpending.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CampaignStrategySpendingValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CampaignStrategySpendingValidationError{}

// Validate checks the field values on Voucher with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Voucher) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Voucher with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in VoucherMultiError, or nil if none found.
func (m *Voucher) ValidateAll() error {
	return m.validate(true)
}

func (m *Voucher) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for TotalVouchers

	if len(errors) > 0 {
		return VoucherMultiError(errors)
	}

	return nil
}

// VoucherMultiError is an error wrapping multiple validation errors returned
// by Voucher.ValidateAll() if the designated constraints aren't met.
type VoucherMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VoucherMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VoucherMultiError) AllErrors() []error { return m }

// VoucherValidationError is the validation error returned by Voucher.Validate
// if the designated constraints aren't met.
type VoucherValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VoucherValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VoucherValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VoucherValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VoucherValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VoucherValidationError) ErrorName() string { return "VoucherValidationError" }

// Error satisfies the builtin error interface
func (e VoucherValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVoucher.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VoucherValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VoucherValidationError{}

// Validate checks the field values on DefineCampaignReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DefineCampaignReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DefineCampaignReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DefineCampaignReplyMultiError, or nil if none found.
func (m *DefineCampaignReply) ValidateAll() error {
	return m.validate(true)
}

func (m *DefineCampaignReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if len(errors) > 0 {
		return DefineCampaignReplyMultiError(errors)
	}

	return nil
}

// DefineCampaignReplyMultiError is an error wrapping multiple validation
// errors returned by DefineCampaignReply.ValidateAll() if the designated
// constraints aren't met.
type DefineCampaignReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DefineCampaignReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DefineCampaignReplyMultiError) AllErrors() []error { return m }

// DefineCampaignReplyValidationError is the validation error returned by
// DefineCampaignReply.Validate if the designated constraints aren't met.
type DefineCampaignReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DefineCampaignReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DefineCampaignReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DefineCampaignReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DefineCampaignReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DefineCampaignReplyValidationError) ErrorName() string {
	return "DefineCampaignReplyValidationError"
}

// Error satisfies the builtin error interface
func (e DefineCampaignReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDefineCampaignReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DefineCampaignReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DefineCampaignReplyValidationError{}
