env: local

logger:
  environment: "dev"
  service_name: "financial_service_example"
  level: debug
  encoding: json
  disable_stacktrace: true

grpc:
  host: 0.0.0.0
  port: 9090

http:
  host: 0.0.0.0
  port: 8080

database:
  address: 0.0.0.0:3306
  user: app_user
  passwd: pwd123
  allow_native_passwords: true
  database_name: financial_service
  max_open_conn: 10
  max_idle_conn: 5
  conn_max_life_time: 10m

redis_connection:
  addr: 0.0.0.0:6379
  db: 0
  pool_size: 10

jwt_token:
  private_key_path: ./config/cert/id_rsa_private_key.txt
  public_key_path: ./config/cert/id_rsa.pub
  token_duration: 1h