// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package da_generated

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createAccountVoucherStmt, err = db.PrepareContext(ctx, createAccountVoucher); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAccountVoucher: %w", err)
	}
	if q.getCampaignAccountByCampaignIdStmt, err = db.PrepareContext(ctx, getCampaignAccountByCampaignId); err != nil {
		return nil, fmt.Errorf("error preparing query GetCampaignAccountByCampaignId: %w", err)
	}
	if q.getCampaignByKeyStmt, err = db.PrepareContext(ctx, getCampaignByKey); err != nil {
		return nil, fmt.Errorf("error preparing query GetCampaignByKey: %w", err)
	}
	if q.insertCampaignStmt, err = db.PrepareContext(ctx, insertCampaign); err != nil {
		return nil, fmt.Errorf("error preparing query InsertCampaign: %w", err)
	}
	if q.insertVoucherStmt, err = db.PrepareContext(ctx, insertVoucher); err != nil {
		return nil, fmt.Errorf("error preparing query InsertVoucher: %w", err)
	}
	if q.updateCampaignByIdStmt, err = db.PrepareContext(ctx, updateCampaignById); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCampaignById: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createAccountVoucherStmt != nil {
		if cerr := q.createAccountVoucherStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAccountVoucherStmt: %w", cerr)
		}
	}
	if q.getCampaignAccountByCampaignIdStmt != nil {
		if cerr := q.getCampaignAccountByCampaignIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCampaignAccountByCampaignIdStmt: %w", cerr)
		}
	}
	if q.getCampaignByKeyStmt != nil {
		if cerr := q.getCampaignByKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCampaignByKeyStmt: %w", cerr)
		}
	}
	if q.insertCampaignStmt != nil {
		if cerr := q.insertCampaignStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertCampaignStmt: %w", cerr)
		}
	}
	if q.insertVoucherStmt != nil {
		if cerr := q.insertVoucherStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertVoucherStmt: %w", cerr)
		}
	}
	if q.updateCampaignByIdStmt != nil {
		if cerr := q.updateCampaignByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCampaignByIdStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                 DBTX
	tx                                 *sql.Tx
	createAccountVoucherStmt           *sql.Stmt
	getCampaignAccountByCampaignIdStmt *sql.Stmt
	getCampaignByKeyStmt               *sql.Stmt
	insertCampaignStmt                 *sql.Stmt
	insertVoucherStmt                  *sql.Stmt
	updateCampaignByIdStmt             *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                 tx,
		tx:                                 tx,
		createAccountVoucherStmt:           q.createAccountVoucherStmt,
		getCampaignAccountByCampaignIdStmt: q.getCampaignAccountByCampaignIdStmt,
		getCampaignByKeyStmt:               q.getCampaignByKeyStmt,
		insertCampaignStmt:                 q.insertCampaignStmt,
		insertVoucherStmt:                  q.insertVoucherStmt,
		updateCampaignByIdStmt:             q.updateCampaignByIdStmt,
	}
}
