// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package da_generated

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

type CampaignStatus string

const (
	CampaignStatusActive   CampaignStatus = "active"
	CampaignStatusInactive CampaignStatus = "inactive"
)

func (e *CampaignStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CampaignStatus(s)
	case string:
		*e = CampaignStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CampaignStatus: %T", src)
	}
	return nil
}

type NullCampaignStatus struct {
	CampaignStatus CampaignStatus `json:"campaign_status"`
	Valid          bool           `json:"valid"` // Valid is true if CampaignStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCampaignStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CampaignStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CampaignStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCampaignStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CampaignStatus), nil
}

type Campaign struct {
	ID     int64          `json:"id"`
	Status CampaignStatus `json:"status"`
	Name   string         `json:"name"`
	// metadata of campaign
	Metadata  json.RawMessage `json:"metadata"`
	CreatedAt sql.NullTime    `json:"created_at"`
	UpdatedAt sql.NullTime    `json:"updated_at"`
}

type CampaignUser struct {
	ID         int64        `json:"id"`
	UserID     int64        `json:"user_id"`
	CampaignID int64        `json:"campaign_id"`
	CreatedAt  sql.NullTime `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
}

type VoucherInfo struct {
	ID          int64  `json:"id"`
	IsActive    bool   `json:"is_active"`
	Name        string `json:"name"`
	Description string `json:"description"`
	// metadata of voucher
	Metadata  json.RawMessage `json:"metadata"`
	CreatedAt sql.NullTime    `json:"created_at"`
	UpdatedAt sql.NullTime    `json:"updated_at"`
}

type VoucherUser struct {
	ID        int64        `json:"id"`
	VoucherID int64        `json:"voucher_id"`
	UserID    int64        `json:"user_id"`
	IsActive  bool         `json:"is_active"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
