// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package da_generated

import (
	"context"
)

type Querier interface {
	CreateVoucherUser(ctx context.Context, arg *CreateVoucherUserParams) (int64, error)
	GetCampaignById(ctx context.Context, id int64) (*Campaign, error)
	InsertVoucher(ctx context.Context, arg *InsertVoucherParams) (int64, error)
	UpdateCampaign(ctx context.Context, arg *UpdateCampaignParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
