// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: table_voucher_info.sql

package da_generated

import (
	"context"
	"encoding/json"
)

const updateVoucher = `-- name: UpdateVoucher :execrows
insert into voucher_info (id, is_active, name, description, metadata)
VALUES (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
     is_active = ?,
     name = ?,
     description = ?,
     metadata = ?
`

type UpdateVoucherParams struct {
	ID          int64           `json:"id"`
	IsActive    bool            `json:"is_active"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Metadata    json.RawMessage `json:"metadata"`
}

func (q *Queries) UpdateVoucher(ctx context.Context, arg *UpdateVoucherParams) (int64, error) {
	result, err := q.exec(ctx, q.updateVoucherStmt, updateVoucher,
		arg.ID,
		arg.IsActive,
		arg.Name,
		arg.Description,
		arg.Metadata,
		arg.IsActive,
		arg.Name,
		arg.Description,
		arg.Metadata,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
