// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: table_account_voucher.sql

package da_generated

import (
	"context"
)

const createAccountVoucher = `-- name: CreateAccountVoucher :execrows
INSERT INTO account_voucher(id, account_id, voucher_id, is_active)
VALUES (?, ?, ?, ?)
`

type CreateAccountVoucherParams struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"account_id"`
	VoucherID int64 `json:"voucher_id"`
	IsActive  bool  `json:"is_active"`
}

func (q *Queries) CreateAccountVoucher(ctx context.Context, arg *CreateAccountVoucherParams) (int64, error) {
	result, err := q.exec(ctx, q.createAccountVoucherStmt, createAccountVoucher,
		arg.ID,
		arg.AccountID,
		arg.VoucherID,
		arg.IsActive,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
