// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: table_voucher.sql

package da_generated

import (
	"context"
	"time"
)

const insertVoucher = `-- name: InsertVoucher :execrows
insert into voucher (voucher_type, amount, is_active, expiration_time, app_id)
VALUES (?, ?, ?, ?, ?)
`

type InsertVoucherParams struct {
	VoucherType    VoucherVoucherType `json:"voucher_type"`
	Amount         string             `json:"amount"`
	IsActive       bool               `json:"is_active"`
	ExpirationTime time.Time          `json:"expiration_time"`
	AppID          string             `json:"app_id"`
}

func (q *Queries) InsertVoucher(ctx context.Context, arg *InsertVoucherParams) (int64, error) {
	result, err := q.exec(ctx, q.insertVoucherStmt, insertVoucher,
		arg.VoucherType,
		arg.Amount,
		arg.IsActive,
		arg.ExpirationTime,
		arg.AppID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
